server:
  port: 8080

spring:
  application:
    name: cn.liumd.test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/book_donation_system?useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
  main:
    allow-circular-references: true
